#!/bin/bash
BASE=$(cd $(dirname $0) && pwd)
cp $BASE/../runtime/bin/* . || exit $?
cat <<EOS >blazor.boot.json || exit $?
{
  "mainAssemblyName": "$1",
  "resources": {
    "jsModuleNative": {
      "dotnet.native.js": "sha256-$(cat dotnet.native.js | openssl dgst -sha256 -binary | openssl base64 -A)"
    },
    "jsModuleRuntime": {
      "dotnet.runtime.js": "sha256-$(cat dotnet.runtime.js | openssl dgst -sha256 -binary | openssl base64 -A)"
    },
    "wasmNative": {
      "dotnet.native.wasm": "sha256-$(cat dotnet.native.wasm | openssl dgst -sha256 -binary | openssl base64 -A)"
    },
    "wasmSymbols": {
      "dotnet.native.js.symbols": "sha256-$(cat dotnet.native.js.symbols | openssl dgst -sha256 -binary | openssl base64 -A)"
    }
  },
  "debugLevel": 0,
  "globalizationMode": "sharded"
}
EOS
shopt -s extglob
if [ -d ../../../bin/Release/net8.0/publish/wwwroot ]; then
	cp -a ../../../bin/Release/net8.0/publish/wwwroot/!(_framework) .. || exit $?
	cp $BASE/serve.json .. || exit $?
fi
