#!/bin/bash
BASE=$(cd $(dirname $0) && pwd)
cd $BASE
if [ "$1" == '' ]; then
	rm -rf il2cxx || exit $?
	dotnet publish -c Release || exit $?
	mkdir -p il2cxx/source || exit $?
	(cd bin/Release/net8.0/browser-wasm/publish && cp\
	 System.Console.dll\
	 System.Runtime.InteropServices.JavaScript.dll\
	 WasmConsole.dll\
	 $BASE/il2cxx/source\
	) || exit $?
	cd il2cxx || exit $?
	dotnet run --project $BASE/../../IL2CXX.Console --target Other --is32\
	 --out out source/WasmConsole.dll\
	 --bundle\
	  'MyClass, WasmConsole'\
	 --reflection\
	  'MyClass, WasmConsole'\
	  'Program, WasmConsole'\
	 || exit $?
	mkdir -p build/_framework || exit $?
	cd build/_framework || exit $?
	emcmake cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=1 ../../out || exit $?
else
	cd il2cxx/build/_framework || exit $?
fi
cmake --build . -j8 || exit $?
../../out/wasm/src/bundle WasmConsole || exit $?
(cd $BASE/bin/Release/net8.0/browser-wasm/AppBundle && cp\
 main.mjs\
 package.json\
 $BASE/il2cxx/build\
) || exit $?
