#!/bin/bash
cd $(dirname $0) || exit $?
dotnet build -c Release || exit $?
dotnet run --project ../../IL2CXX.Console --target Unix --check-null\
 --out out bin/Release/net10.0/NumericsTests.dll\
 --bundle\
  'System.Numerics.Tests.GenericVectorTests, NumericsTests'\
  'System.Numerics.Tests.GenericVectorUnsupportedTests, NumericsTests'\
  'System.Numerics.Tests.Matrix3x2Tests, NumericsTests'\
  'System.Numerics.Tests.Matrix4x4Tests, NumericsTests'\
  'System.Numerics.Tests.PlaneTests, NumericsTests'\
  'System.Numerics.Tests.QuaternionTests, NumericsTests'\
  'System.Numerics.Tests.Vector2Tests, NumericsTests'\
  'System.Numerics.Tests.Vector3Tests, NumericsTests'\
  'System.Numerics.Tests.Vector4Tests, NumericsTests'\
 --reflection\
  'System.Numerics.Vector, System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Byte, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.SByte, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.UInt16, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Int16, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.UInt32, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Int32, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.UInt64, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Int64, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.IntPtr, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.UIntPtr, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Single, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Double, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Boolean, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Char, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Half, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.Int128, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Numerics.Vector`1[[System.UInt128, System.Private.CoreLib]], System.Private.CoreLib'\
  'System.Tests.GenericMathTestMemberData, NumericsTests'\
  'System.Numerics.Tests.GenericVectorTests, NumericsTests'\
  'System.Numerics.Tests.GenericVectorUnsupportedTests, NumericsTests'\
  'System.Numerics.Tests.Matrix3x2Tests, NumericsTests'\
  'System.Numerics.Tests.Matrix4x4Tests, NumericsTests'\
  'System.Numerics.Tests.PlaneTests, NumericsTests'\
  'System.Numerics.Tests.QuaternionTests, NumericsTests'\
  'System.Numerics.Tests.Vector2Tests, NumericsTests'\
  'System.Numerics.Tests.Vector3Tests, NumericsTests'\
  'System.Numerics.Tests.Vector4Tests, NumericsTests'\
 || exit $?
mkdir out/build || exit $?
cd out/build || exit $?
CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=1 -DCMAKE_CXX_FLAGS='-fno-strict-aliasing' -DCMAKE_EXE_LINKER_FLAGS='-Oz' .. || exit $?
#CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Debug .. || exit $?
cmake --build . -j8 || exit $?
