<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>IL2CXX_OVERRIDE_NUMERICS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="src/*;src/recyclone/CMakeLists.txt;src/recyclone/include/**;src/recyclone/test/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
