#!/bin/bash
DOTNET_ROOT=~/.local/dotnet
BASE=$(cd $(dirname $0) && pwd)
cd $BASE
if [ "$1" == '' ]; then
	dotnet publish -c Release || exit $?
	rm -rf il2cxx || exit $?
	mkdir -p il2cxx/source || exit $?
	(cd bin/Release/net6.0 && cp\
	 Microsoft.AspNetCore.Components.WebAssembly.dll\
	 Microsoft.JSInterop.WebAssembly.dll\
	 System.Net.Http.dll\
	 System.Private.Runtime.InteropServices.JavaScript.dll\
	 BepuPhysics.dll\
	 BepuUtilities.dll\
	 Blazor.Extensions.Canvas.dll\
	 DemoContentLoader.dll\
	 BPDemosBW.dll\
	 $BASE/il2cxx/source\
	) || exit $?
	cp -a bin/Release/net6.0/publish/wwwroot il2cxx || exit $?
	rm -rf il2cxx/wwwroot/_framework || exit $?
	cd il2cxx || exit $?
	ln -s ../out/build/_framework wwwroot/_framework || exit $?
	dotnet run --project $BASE/../../IL2CXX.Console --target Other --is32\
	 --assemblies $DOTNET_ROOT/shared/Microsoft.AspNetCore.App/6.0.4\
	 --out out source/BPDemosBW.dll\
	 --bundle\
	  'System.Text.Json.Serialization.Converters.ArrayConverter`2[[System.Object[], System.Private.CoreLib], [System.Object, System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ArrayConverter`2[[System.Object[][], System.Private.CoreLib], [System.Object[], System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ArrayConverter`2[[Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web], [Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter, Microsoft.AspNetCore.Components.Web]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib], [System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib], [System.String, System.Private.CoreLib], [System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib], [Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web]], System.Private.CoreLib], [System.String, System.Private.CoreLib], [Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BlendingEquation, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BlendingMode, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BlitFilter, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BufferBits, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BufferType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BufferUsageHint, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.CompareFunction, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.DataType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.EnableCap, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.FramebufferAttachment, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.FramebufferType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.PixelFormat, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.PixelType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.Primitive, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.ShaderType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.Texture2DType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.TextureType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.TextureParameter, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.TextureParameterValue, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ListOfTConverter`2[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib], [System.String, System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.JSInterop.DotNetObjectReference`1[[Microsoft.AspNetCore.Components.RenderTree.WebRenderer+WebRendererInteropMethods, Microsoft.AspNetCore.Components.Web]], Microsoft.JSInterop]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLBuffer, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLFramebuffer, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLProgram, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLShader, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLTexture, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLVertexArrayObject, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Runtime.InteropServices.JavaScript.Runtime, System.Private.Runtime.InteropServices.JavaScript'\
	  'Microsoft.Extensions.Options.OptionsCache`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.Extensions.Logging.LoggerFactoryOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.OptionsMonitor`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.UnnamedOptionsManager`1[[Microsoft.Extensions.Logging.LoggerFactoryOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Logging.Logger`1[[Microsoft.AspNetCore.Components.Infrastructure.ComponentStatePersistenceManager, Microsoft.AspNetCore.Components]], Microsoft.Extensions.Logging.Abstractions'\
	  'Microsoft.JSInterop.Infrastructure.DotNetObjectReferenceJsonConverter`1[[Microsoft.AspNetCore.Components.RenderTree.WebRenderer+WebRendererInteropMethods, Microsoft.AspNetCore.Components.Web]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.DotNetObjectReferenceJsonConverter`1[[BPDemosBW.Pages.Index, BPDemosBW]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TaskResultGetter`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.Int32, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.Object, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.String, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.UInt32, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLBuffer, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLFramebuffer, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLProgram, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLShader, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLTexture, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLVertexArrayObject, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.LayoutView, Microsoft.AspNetCore.Components; System.Type, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.LayoutView, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.RenderFragment, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.RouteView, Microsoft.AspNetCore.Components; System.Type, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.RouteView, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.NavigationManager, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.RouteView, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.RouteData, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.FocusOnNavigate, Microsoft.AspNetCore.Components.Web; System.String, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.FocusOnNavigate, Microsoft.AspNetCore.Components.Web; Microsoft.JSInterop.IJSRuntime, Microsoft.JSInterop'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.FocusOnNavigate, Microsoft.AspNetCore.Components.Web; Microsoft.AspNetCore.Components.RouteData, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.NavLink, Microsoft.AspNetCore.Components.Web; System.String, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.NavLink, Microsoft.AspNetCore.Components.Web; System.Collections.Generic.IReadOnlyDictionary`2[[System.String, System.Private.CoreLib], [System.Object, System.Private.CoreLib]], System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.NavLink, Microsoft.AspNetCore.Components.Web; Microsoft.AspNetCore.Components.NavigationManager, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.NavLink, Microsoft.AspNetCore.Components.Web; Microsoft.AspNetCore.Components.RenderFragment, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.NavLink, Microsoft.AspNetCore.Components.Web; Microsoft.AspNetCore.Components.Routing.NavLinkMatch, Microsoft.AspNetCore.Components.Web'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; System.Boolean, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; System.Reflection.Assembly, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; System.Collections.Generic.IEnumerable`1[[System.Reflection.Assembly, System.Private.CoreLib]], System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; Microsoft.Extensions.Logging.ILoggerFactory, Microsoft.Extensions.Logging.Abstractions'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.EventCallback`1[[Microsoft.AspNetCore.Components.Routing.NavigationContext, Microsoft.AspNetCore.Components]], Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.NavigationManager, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.RenderFragment, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.RenderFragment`1[[Microsoft.AspNetCore.Components.RouteData, Microsoft.AspNetCore.Components]], Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.Routing.INavigationInterception, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Sections.SectionContent, Microsoft.AspNetCore.Components; System.Boolean, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Sections.SectionContent, Microsoft.AspNetCore.Components; System.String, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Sections.SectionContent, Microsoft.AspNetCore.Components; Microsoft.AspNetCore.Components.RenderFragment, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Sections.SectionOutlet, Microsoft.AspNetCore.Components; System.String, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Web.HeadOutlet, Microsoft.AspNetCore.Components.Web; Microsoft.JSInterop.IJSRuntime, Microsoft.JSInterop'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Microsoft.AspNetCore.Components.Web.PageTitle, Microsoft.AspNetCore.Components.Web; Microsoft.AspNetCore.Components.RenderFragment, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Blazor.Extensions.Canvas.BECanvas, Blazor.Extensions.Canvas; System.Int64, System.Private.CoreLib'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) Blazor.Extensions.Canvas.BECanvas, Blazor.Extensions.Canvas; Microsoft.JSInterop.IJSRuntime, Microsoft.JSInterop'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) BPDemosBW.Pages.Index, BPDemosBW; Microsoft.JSInterop.IJSRuntime, Microsoft.JSInterop'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components: CallPropertySetter`2(System.Action`2[0, 1], System.Private.CoreLib; System.Object, System.Private.CoreLib; System.Object, System.Private.CoreLib) BPDemosBW.Shared.MainLayout, BPDemosBW; Microsoft.AspNetCore.Components.RenderFragment, Microsoft.AspNetCore.Components'\
	  'BPDemosBW.Pages.Index, BPDemosBW'\
	 --reflection\
	  'System.Action`1[[Microsoft.AspNetCore.Components.Web.KeyboardEventArgs, Microsoft.AspNetCore.Components.Web]], System.Private.CoreLib'\
	  'System.Action`1[[Microsoft.AspNetCore.Components.Web.MouseEventArgs, Microsoft.AspNetCore.Components.Web]], System.Private.CoreLib'\
	  'System.Action`1[[Microsoft.AspNetCore.Components.Web.WheelEventArgs, Microsoft.AspNetCore.Components.Web]], System.Private.CoreLib'\
	  'System.Boolean, System.Private.CoreLib'\
	  'System.Byte, System.Private.CoreLib'\
	  'System.Byte[], System.Private.CoreLib'\
	  'System.Double, System.Private.CoreLib'\
	  'System.Func`2[[Microsoft.AspNetCore.Components.Web.KeyboardEventArgs, Microsoft.AspNetCore.Components.Web], [System.Threading.Tasks.Task, System.Private.CoreLib]], System.Private.CoreLib'\
	  'System.Func`2[[Microsoft.AspNetCore.Components.Web.MouseEventArgs, Microsoft.AspNetCore.Components.Web], [System.Threading.Tasks.Task, System.Private.CoreLib]], System.Private.CoreLib'\
	  'System.Int32, System.Private.CoreLib'\
	  'System.Int64, System.Private.CoreLib'\
	  'System.Object, System.Private.CoreLib'\
	  'System.Object[], System.Private.CoreLib'\
	  'System.Object[][], System.Private.CoreLib'\
	  'System.Single, System.Private.CoreLib'\
	  'System.String, System.Private.CoreLib'\
	  'System.UInt32, System.Private.CoreLib'\
	  'System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib], [System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib'\
	  'System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib], [Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web]], System.Private.CoreLib'\
	  'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib'\
	  'System.Text.Json.JsonElement, System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ArrayConverter`2[[System.Object[], System.Private.CoreLib], [System.Object, System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ArrayConverter`2[[System.Object[][], System.Private.CoreLib], [System.Object[], System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ArrayConverter`2[[Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web], [Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter, Microsoft.AspNetCore.Components.Web]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib], [System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib], [System.String, System.Private.CoreLib], [System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib], [Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web]], System.Private.CoreLib], [System.String, System.Private.CoreLib], [Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BlendingEquation, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BlendingMode, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BlitFilter, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BufferBits, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BufferType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.BufferUsageHint, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.CompareFunction, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.DataType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.EnableCap, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.FramebufferAttachment, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.FramebufferType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.PixelFormat, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.PixelType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.Primitive, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.ShaderType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.Texture2DType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.TextureType, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.TextureParameter, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Blazor.Extensions.Canvas.WebGL.TextureParameterValue, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ListOfTConverter`2[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib], [System.String, System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.JSInterop.DotNetObjectReference`1[[Microsoft.AspNetCore.Components.RenderTree.WebRenderer+WebRendererInteropMethods, Microsoft.AspNetCore.Components.Web]], Microsoft.JSInterop]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLBuffer, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLFramebuffer, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLProgram, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLShader, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLTexture, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazor.Extensions.Canvas.WebGL.WebGLVertexArrayObject, Blazor.Extensions.Canvas]], System.Text.Json'\
	  'System.Threading.Tasks.Task`1, System.Private.CoreLib'\
	  'System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib'\
	  'System.Runtime.InteropServices.JavaScript.Runtime, System.Private.Runtime.InteropServices.JavaScript'\
	  'Microsoft.Extensions.Options.OptionsCache`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.Extensions.Logging.LoggerFactoryOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.OptionsMonitor`1[[Microsoft.Extensions.Logging.LoggerFilterOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Options.UnnamedOptionsManager`1[[Microsoft.Extensions.Logging.LoggerFactoryOptions, Microsoft.Extensions.Logging]], Microsoft.Extensions.Options'\
	  'Microsoft.Extensions.Logging.LoggerFactory, Microsoft.Extensions.Logging'\
	  'Microsoft.Extensions.Logging.Logger`1[[Microsoft.AspNetCore.Components.Infrastructure.ComponentStatePersistenceManager, Microsoft.AspNetCore.Components]], Microsoft.Extensions.Logging.Abstractions'\
	  'Microsoft.JSInterop.DotNetObjectReference`1[[Microsoft.AspNetCore.Components.RenderTree.WebRenderer+WebRendererInteropMethods, Microsoft.AspNetCore.Components.Web]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.DotNetObjectReference`1[[BPDemosBW.Pages.Index, BPDemosBW]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.DotNetObjectReferenceJsonConverter`1[[Microsoft.AspNetCore.Components.RenderTree.WebRenderer+WebRendererInteropMethods, Microsoft.AspNetCore.Components.Web]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.DotNetObjectReferenceJsonConverter`1[[BPDemosBW.Pages.Index, BPDemosBW]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TaskResultGetter`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.Int32, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.Object, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.String, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[System.UInt32, System.Private.CoreLib]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLBuffer, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLFramebuffer, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLProgram, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLShader, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLTexture, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.JSInterop.Infrastructure.TaskGenericsUtil+TcsResultSetter`1[[Blazor.Extensions.Canvas.WebGL.WebGLVertexArrayObject, Blazor.Extensions.Canvas]], Microsoft.JSInterop'\
	  'Microsoft.AspNetCore.Components.ComponentBase, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.ElementReference, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Infrastructure.ComponentStatePersistenceManager, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.LayoutComponentBase, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.LayoutView, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Reflection.PropertySetter, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameType, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.RenderTree.WebRenderer+WebRendererInteropMethods, Microsoft.AspNetCore.Components.Web'\
	  'Microsoft.AspNetCore.Components.RouteView, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Routing.FocusOnNavigate, Microsoft.AspNetCore.Components.Web'\
	  'Microsoft.AspNetCore.Components.Routing.NavLink, Microsoft.AspNetCore.Components.Web'\
	  'Microsoft.AspNetCore.Components.Routing.Router, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Sections.SectionContent, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Sections.SectionOutlet, Microsoft.AspNetCore.Components'\
	  'Microsoft.AspNetCore.Components.Web.HeadOutlet, Microsoft.AspNetCore.Components.Web'\
	  'Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore+JSComponentParameter[], Microsoft.AspNetCore.Components.Web'\
	  'Microsoft.AspNetCore.Components.Web.PageTitle, Microsoft.AspNetCore.Components.Web'\
	  'Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods, Microsoft.AspNetCore.Components.WebAssembly'\
	  'Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime, Microsoft.AspNetCore.Components.WebAssembly'\
	  'Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyConsoleLoggerProvider, Microsoft.AspNetCore.Components.WebAssembly'\
	  'BepuPhysics.Constraints.AngularAxisGearMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.AngularAxisMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.AngularHingeTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.AngularMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.AngularServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.AngularSwivelHingeTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.AreaConstraintTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.BallSocketMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.BallSocketServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.BallSocketTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.CenterDistanceLimitTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.CenterDistanceTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.DistanceLimitTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.DistanceServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.HingeTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.LinearAxisLimitTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.LinearAxisMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.LinearAxisServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.OneBodyAngularMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.OneBodyAngularServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.OneBodyLinearMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.OneBodyLinearServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.PointOnLineServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.SwingLimitTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.SwivelHingeTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.TwistLimitTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.TwistMotorTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.TwistServoTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.VolumeConstraintTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.WeldTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact2NonconvexOneBodyTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact3NonconvexOneBodyTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact4NonconvexOneBodyTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact2NonconvexTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact3NonconvexTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact4NonconvexTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact1OneBodyTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact2OneBodyTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact3OneBodyTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact4OneBodyTypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact1TypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact2TypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact3TypeProcessor, BepuPhysics'\
	  'BepuPhysics.Constraints.Contact.Contact4TypeProcessor, BepuPhysics'\
	  'Demos.Demos.Characters.DynamicCharacterMotionTypeProcessor, BPDemosBW'\
	  'Demos.Demos.Characters.StaticCharacterMotionTypeProcessor, BPDemosBW'\
	  'Blazor.Extensions.BECanvasComponent, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.BECanvas, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.BlendingEquation, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.BlendingMode, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.BlitFilter, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.BufferBits, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.BufferType, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.BufferUsageHint, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.CompareFunction, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.DataType, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.EnableCap, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.FramebufferAttachment, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.FramebufferType, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.PixelFormat, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.PixelType, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.Primitive, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.ShaderType, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.Texture2DType, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.TextureType, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.TextureParameter, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.TextureParameterValue, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.WebGLBuffer, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.WebGLFramebuffer, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.WebGLObject, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.WebGLProgram, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.WebGLShader, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.WebGLTexture, Blazor.Extensions.Canvas'\
	  'Blazor.Extensions.Canvas.WebGL.WebGLVertexArrayObject, Blazor.Extensions.Canvas'\
	  'BPDemosBW.App, BPDemosBW'\
	  'BPDemosBW.Pages.Index, BPDemosBW'\
	  'BPDemosBW.Shared.MainLayout, BPDemosBW'\
	  'Program, BPDemosBW'\
	 || exit $?
	mkdir out/build || exit $?
	cd out/build || exit $?
	emcmake cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=1 -DCMAKE_CXX_FLAGS='-msimd128' -DCMAKE_EXE_LINKER_FLAGS="-s INITIAL_MEMORY=1073741824 -s PTHREAD_POOL_SIZE='4 + Math.max(0, navigator.hardwareConcurrency - (navigator.hardwareConcurrency > 4 ? 3 : 2)) * 2' -O1" .. || exit $?
else
	cd il2cxx/out/build || exit $?
fi
cmake --build . -j8 || exit $?
rm -rf _framework || exit $?
cp -a ../wasm/_framework . || exit $?
cp dotnet.js dotnet.worker.js dotnet.wasm _framework || exit $?
cd _framework || exit $?
sed -i '/assert(runtimeInitialized,/d' dotnet.js || exit $?
sed -i 's/"entryAssembly": ""/"entryAssembly": "BPDemosBW"/' blazor.boot.json || exit $?
sed -i "s/\"dotnet\\.js\": \"sha256-.*\"/\"dotnet.js\": \"sha256-$(cat dotnet.js | openssl dgst -sha256 -binary | openssl base64 -A | sed 's/\//\\\//g')\"/" blazor.boot.json || exit $?
sed -i "s/\"dotnet\\.worker\\.js\": \"sha256-.*\"/\"dotnet.worker.js\": \"sha256-$(cat dotnet.worker.js | openssl dgst -sha256 -binary | openssl base64 -A | sed 's/\//\\\//g')\"/" blazor.boot.json || exit $?
sed -i "s/\"dotnet\\.wasm\": \"sha256-.*\"/\"dotnet.wasm\": \"sha256-$(cat dotnet.wasm | openssl dgst -sha256 -binary | openssl base64 -A | sed 's/\//\\\//g')\"/" blazor.boot.json || exit $?
