#!/bin/bash
BASE=$(cd $(dirname $0) && pwd)
cd $BASE
if [ "$1" == '' ]; then
	rm -rf il2cxx || exit $?
	dotnet publish -c Release || exit $?
	mkdir -p il2cxx/source || exit $?
	(cd bin/Release/net8.0 && cp\
	 System.Runtime.InteropServices.JavaScript.dll\
	 ThinJS.WebGL.dll\
	 WebGLGears.dll\
	 $BASE/il2cxx/source\
	) || exit $?
	cd il2cxx || exit $?
	dotnet run --project $BASE/../../IL2CXX.Console --target Other --is32\
	 --out out source/WebGLGears.dll\
	 --reflection\
	  'Program, WebGLGears'\
	 || exit $?
	mkdir -p wwwroot/_framework || exit $?
	cd wwwroot/_framework || exit $?
	emcmake cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=1 -DCMAKE_CXX_FLAGS='-msimd128' ../../out || exit $?
else
	cd il2cxx/wwwroot/_framework || exit $?
fi
cmake --build . -j8 || exit $?
../../out/wasm/src/bundle WebGLGears || exit $?
