#!/bin/bash
BASE=$(cd $(dirname $0) && pwd)
SOURCE=$BASE/../../externals/MonoGame.Samples/Platformer2D/Desktop
cd $BASE
dotnet build $SOURCE -c Release || exit $?
dotnet run --project ../../IL2CXX.Console --target Unix\
 --out out $SOURCE/bin/Release/net10.0/Platformer2D.dll\
 --bundle\
  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Platformer2D.Core.Effects.ParticleEffectType, Core]], System.Text.Json'\
  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Platformer2D.Core.Settings.Platformer2DLeaderboard, Core]], System.Text.Json'\
  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Platformer2D.Core.Settings.Platformer2DSettings, Core]], System.Text.Json'\
  'System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Platformer2D.Core.Effects.ParticleEffectType, Core]], System.Text.Json'\
 --reflection\
  'System.Text.Json.Serialization.Converters.EnumConverter`1[[Platformer2D.Core.Effects.ParticleEffectType, Core]], System.Text.Json'\
  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Platformer2D.Core.Settings.Platformer2DLeaderboard, Core]], System.Text.Json'\
  'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Platformer2D.Core.Settings.Platformer2DSettings, Core]], System.Text.Json'\
  'System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Boolean, System.Private.CoreLib]], System.Text.Json'\
  'System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Int32, System.Private.CoreLib]], System.Text.Json'\
  'System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.TimeSpan, System.Private.CoreLib]], System.Text.Json'\
  'System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Platformer2D.Core.Effects.ParticleEffectType, Core]], System.Text.Json'\
  'Microsoft.Xna.Framework.Content.CharReader, MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.Int32Reader, MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib]], MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle, MonoGame.Framework]], MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Vector3, MonoGame.Framework]], MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.RectangleReader, MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.SongReader, MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.SoundEffectReader, MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.Texture2DReader, MonoGame.Framework'\
  'Microsoft.Xna.Framework.Content.Vector3Reader, MonoGame.Framework'\
  'Platformer2D.Core.Effects.ParticleEffectType, Core'\
  'Platformer2D.Core.Settings.Platformer2DLeaderboard, Core'\
  'Platformer2D.Core.Settings.Platformer2DSettings, Core'\
  'Program, Platformer2D'\
 || exit $?
mkdir out/build || exit $?
cd out/build || exit $?
CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=1 -DCMAKE_EXE_LINKER_FLAGS='-Oz' .. || exit $?
cmake --build . -j8 || exit $?
cp -a $SOURCE/bin/Release/net10.0/Content . || exit $?
